---

- name: "Create vim folder"
  file:
    path: "{{ vundle_path }}"
    state: directory
    mode: "0644"

- name: "Create config folder"
  file:
      path: "{{ config_folder }}"
      state: directory
      mode: "0644"
