---

- name: "Install default useful programs"
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ program_list }}"

- name: "Create config folder if not exists"
  file:
    path: "{{ config_folder }}"
    state: directory
    mode: "0644"

