---

- name: "Install default useful programs"
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ program_list }}"

- name: "Ohmyzsh folder"
  stat:
    path: "{{ ohmyzsh_path }}"
  register: ohmyzsh_folder

- name: "Vundle folder"
  stat:
    path: "{{ vundle_path }}"
  register: vundle_folder

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists

- name: "Install Vundle"
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vundle_path }}"
  when: not vundle_folder.exists
