---

- name: "Installing update script"
  template:
    src: update_repos.j2
    dest: "{{ init_script_location }}"
    follow: yes
  become: true

- name: "Changing file mode"
  file:
    path: "{{ init_script_location }}"
    mode: 'a+x'
  become: true

- name: "Installing the file in a cronjob"
  cron:
    - name: "Updating user configuration repos"
      special_time: reboot
      job: "{{ init_script_location }}"
