---

- name: "Creating vim folder"
  file:
    path: "{{ vim_folder }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Creating vim bundle folder"
  file:
    path: "{{ vim_bundle_folder }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Installing Vundle"
  git:
    repo: "{{ vundle_repo }}"
    dest: "{{ vundle_path }}"

- name: "Installing vim plugins"
  command: vim +PluginInstall +qall
  args:
    removes: $HOME/.config/vim/bundle/Vundle.vim
    executable: /bin/bash
  ignore_errors: true

- name: "Compiling the YCM plugin"
  script: "{{ ycm_script }}"
  args:
    removes: "{{ ycm_script }}"
    executable: python3
