---

- name: "Ohmyzsh folder"
  stat:
    path: "{{ ohmyzsh_path }}"
  register: ohmyzsh_folder

- name: "Default ohmyzsh folder"
  stat:
    path: $HOME/.oh-my-zsh/
  register: ohmyzsh_default_folder

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists
  ignore_errors: true

- name: "Creating zsh folder"
  file:
    path: "{{ zsh_folder }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Moving the old oh-my-zsh file"
  shell:
    cmd: "mv $HOME/.oh-my-zsh $HOME/.config/oh-my-zsh"

- name: "Create Symbolic link for ZSH"
  file:
    src: "{{ zshrc_file }}"
    dest: "{{ zshrc_link }}"
    state: link

- name: "Change default shell to ZSH"
  user:
    name: "{{ ansible_user }}"
    shell: "/usr/bin/zsh"
  become: true

- name: "Change default shell for root"
  user:
    name: "root"
    shell: "/usr/bin/zsh"
  become: true

- name: "Create Symlink for zshenv"
  file:
    src: "{{ zshenv_file }}"
    dest: "{{ zshenv_link }}"
    state: link

- name: "Removing default zshrc"
  file:
    path: "{{ zshrc_default }}"
    state: absent

- name: "Installing zsh-syntax-highlighting"
  git:
    repo: "{{ zsh_syntax_highlighting_repo }}"
    dest: "{{ zsh_syntax_highlighting_path }}"
