---

- name: "Ohmyzsh folder"
  stat:
    path: "{{ ohmyzsh_path }}"
  register: ohmyzsh_folder

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists
  ignore_errors: true

- name: "Creating zsh folder"
  file:
    path: "{{ zsh_folder }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Create Symbolic link for ZSH"
  file:
    src: "{{ zshrc_link }}"
    dest: "{{ zshrc_file }}"
    state: link

- name: "Change default shell to ZSH"
  user:
    name: "{{ ansible_user }}"
    shell: "zsh"
  become: true
