---

- name: "Installing zsh-syntax-highlighting"
  git:
    repo: "{{ zsh_syntax_highlighting_repo }}"
    dest: "{{ zsh_syntax_highlighting_path }}"

- name: "Installing zsh-z"
  git:
    repo: "{{ zsh_zsh_z_repo }}"
    dest: "{{ zsh_zsh_z_path }}"
